#!/usr/bin/env bun
import { isDev } from '@/utils/utils'
import { build } from 'esbuild'
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

type BuildTarget = {
  entryRelative: string
  outFileRelative: string
  globalName: string
  constName: string
}

async function buildAndWriteBundle(target: BuildTarget, projectRoot: string, sourcemap: 'inline' | false) {
  const entry = path.resolve(projectRoot, target.entryRelative)
  const outFile = path.resolve(projectRoot, target.outFileRelative)

  const result = await build({
    entryPoints: [entry],
    write: false,
    bundle: true,
    minify: true,
    platform: 'browser',
    format: 'iife',
    globalName: target.globalName,
    target: ['es2018'],
    legalComments: 'none',
    sourcemap,
  })

  const outputFile = result.outputFiles?.[0]
  if (!outputFile?.text) {
    throw new Error(`Failed to produce bundled runtime for ${target.globalName}`)
  }
  const js = outputFile.text

  const header =
    `// @generated by scripts/build-runtimes.ts\n` + `// Do not edit manually.\n` + `/* eslint-disable */\n`
  const content = `${header}export const ${target.constName}: string = ${JSON.stringify(js)}\n`
  await writeFile(outFile, content, 'utf8')
  console.log(`Wrote ${target.globalName} bundle to ${outFile} (${js.length} bytes)`)
}

export async function buildRuntimes() {
  const projectRoot = path.resolve(__dirname, '..')
  const sourcemap = isDev() ? 'inline' : false

  // Build presence runtime
  await buildAndWriteBundle(
    {
      entryRelative: 'src/utils/presence-script.ts',
      outFileRelative: 'src/utils/presence-bundle.ts',
      globalName: 'PresenceRuntime',
      constName: 'PRESENCE_RUNTIME_BUNDLE',
    },
    projectRoot,
    sourcemap,
  )

  // Build theme runtime
  await buildAndWriteBundle(
    {
      entryRelative: 'src/utils/theme-script.ts',
      outFileRelative: 'src/utils/theme-bundle.ts',
      globalName: 'ThemeRuntime',
      constName: 'THEME_RUNTIME_BUNDLE',
    },
    projectRoot,
    sourcemap,
  )
}

if (import.meta.main) {
  await buildRuntimes().catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err)
    console.error(msg)
    process.exit(1)
  })
}
