#!/usr/bin/env bun
import { isDev } from '@/utils/utils'
import { build } from 'esbuild'
import { writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

async function main() {
  const projectRoot = resolve(__dirname, '..')
  const entry = resolve(projectRoot, 'src/utils/theme-script.ts')
  const outFile = resolve(projectRoot, 'src/utils/theme-bundle.ts')
  const sourcemap = isDev() ? 'inline' : false

  const result = await build({
    entryPoints: [entry],
    write: false,
    bundle: true,
    minify: true,
    platform: 'browser',
    format: 'iife',
    globalName: 'ThemeRuntime',
    target: ['es2018'],
    legalComments: 'none',
    sourcemap,
  })

  const outputFile = result.outputFiles?.[0]
  if (!outputFile?.text) {
    throw new Error('Failed to produce bundled theme runtime')
  }
  const js = outputFile.text

  const header =
    `// @generated by scripts/build-theme-runtime.ts\n` + `// Do not edit manually.\n` + `/* eslint-disable */\n`
  const content = `${header}export const THEME_RUNTIME_BUNDLE: string = ${JSON.stringify(js)}\n`
  await writeFile(outFile, content, 'utf8')
  console.log(`Wrote theme bundle to ${outFile} (${js.length} bytes)`)
}

main().catch((err: unknown) => {
  const msg = err instanceof Error ? err.message : String(err)
  console.error(msg)
  process.exit(1)
})
