export const CONVEX_DEPLOY_BUILD_COMMAND = 'bun scripts/vercel-build-command.ts'
export const CONVEX_DEPLOY_URL_CAPTURE_ENV = 'KIL_DEV_CONVEX_DEPLOY_URL_CAPTURE_PATH'
export const CONVEX_DEPLOY_URL_ENV_VAR_NAME = 'NEXT_PUBLIC_CONVEX_URL'
