name: Lint

on:
  push:
    branches: ['*', '*/*', '**']
  pull_request:
    branches: ['*', '*/*', '**']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint
        env:
          SKIP_ENV_VALIDATION: true

      - name: Check TypeScript types
        run: bun run typecheck

      - name: Check Prettier formatting
        run: bun run format:check
